name: Auto Commit 2

on:
  push:
    branches:
      - master
      
  schedule:
    # Run Auto Commit every 20 minute(s)
    - cron: "*/20 * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Run Bot Task
        run: |
          chmod +x ./task.sh
          ./task.sh
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GH_TOKEN }}
          
      - name: send telegram message (notification)
        run: |
            function sendTG() {
            curl -s "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendmessage" --data "text=${*}&chat_id=${{ secrets.TG_CHAT_ID }}&parse_mode=Markdown"
            }
            sendTG "\`I have pushed new action to GitHub\` %0A> [[action are here](${{ secrets.ACTIONS_URL }})]" &> /dev/null
