name: rapi's butt

on:
  push:
    branches:
      - master
      
  schedule:
    # run auto commit time
    - cron: "0 0-23 * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
          persist-credentials: false
          fetch-depth: 0
          
      # Set Timezone
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Jakarta"
          timezoneMacos: "Asia/Jakarta"
          timezoneWindows: "Jakarta"
          
      - name: Run Bot Task
        run: | # change task-*.sh, default is task-ori.sh
          chmod +x ./task-mnmlist.sh
          ./task-mnmlist.sh
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          
      - name: Send Notification # action notifier by telegram bot
        run: |
            function sendTG() {
            curl -s "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendmessage" --data "text=${*}&chat_id=${{ secrets.TG_CHAT_ID }}&parse_mode=Markdown"
            }
            sendTG "\`I have pushed new action to GitHub\` %0A> [action are here](${{ secrets.ACTIONS_URL }})" &> /dev/null
